### ISSUE TITLE
Make separate environment for testing and production

### ISSUE THREAD

**Issue by nandrian-usc** [Khider-GarijoCORP/MyWonder_App#2]
**Is your Task related to any problem? Describe**
When doing demo, it is important to not do testing or inputting in production environment. Therefore we need separate environment for testing which can be filled with dummy examples and being overwritten anytime without disturbing production environment

**Proposed Solution**
Make 2 separate environment, one for testing and one for production

**Task**
- [x] 1. Make testing environment
- [x] 2. Recreate or clean up production environment
- [x] 3. Make documentation of environment configuration
