### ISSUE TITLE
Change contents and technical terminologies to be user friendly

### ISSUE THREAD

**Issue by nandrian-usc** [Khider-GarijoCORP/MyWonder_App#3]
**Is your feature request related to a problem? Please describe.**
Many contents and terminologies in MyWonder are too technical and not user friendly for common people, even the CEO was not familiar with them. 

**Describe the solution you'd like**
We need to evaluate the contents and redesign them again with mindset of common people. The changes should be implemented in MyWonder and tested again by involving common people (perhaps invite one from Customer Assistance team). 

**Describe alternatives you've considered**
Even if a terminology do not have common terminology, we should provide some kind of glossary or tooltip description under the label.

**Additional context**
-

**Task**
- [x] 1. Requirement and content analysis 
- [x] 2. Design new contents and terminologies 
- [x] 3. Implement content and terminologies updates to MyWonder
- [x] 4. Acceptance Test and fixes
