### ISSUE TITLE
Add Note feature to Visualization

### ISSUE THREAD

**Issue by nandrian-usc** [Khider-GarijoCORP/MyWonder_App#4]
**Is your feature request related to a problem? Please describe.**
MyWonder currently don't have area to put "Note" in its visualization. This Note is needed for user to document what they're doing and why

**Describe the solution you'd like**
A textarea or richtext editor should be enough, but first we need to evaluate existing design (storage and configuration) whether it can accommodate this one Note field addition. Implementation should be tested before release.

**Describe alternatives you've considered**
None

**Additional context**
None

**Task**
- [x] 1. Analyze existing design of MyWonder and select where to slip the new Note field
- [x] 2. Implement Note to MyWonder
- [x] 3. Update scenario test
- [x] 4. Unit test and fix (doc: Bugs list and retest documentation)
- [x] 5. Acceptance test
