### ISSUE TITLE
Add Help & Documentation as menu and page

### ISSUE THREAD

**Issue by nandrian-usc** [Khider-GarijoCORP/MyWonder_App#5]
**Is your feature request related to a problem? Please describe.**
One of the reason why user contacted Customer Assistance was because they might didn't have easy access resource to documentation or FAQ. This may result in busier workload for Customer Assistance Team.

**Describe the solution you'd like**
Let's have the documentation (user guide, walkthrough, and FAQ) in the MyWonder menu as something accessible or downloadable so that user can find them anytime anywhere. It will be helpful to answer question regarding how to do visualization. Also glossaries of technical terminologies can also be found here.

**Describe alternatives you've considered**
None

**Additional context**
None

**Task**
- [x] 1. Analyze requirement with regard to existing design of MyWonder
- [x] 2. Design the feature
- [x] 3. Implement feature to MyWonder
- [x] 4. Create scenario test
- [x] 5. Unit test and fix 
- [ ] 6. Acceptance test
