### ISSUE TITLE
Add Content-Update Interface for easy future content update

### ISSUE THREAD

**Issue by nandrian-usc** [Khider-GarijoCORP/MyWonder_App#6]
**Is your feature request related to a problem? Please describe.**
Change in content can only be executed by backend developer. Change in contents and terminologies may still happen even in the future (during maintenance phase), it just simply inconvenient to always asking designer and then waiting them to contact developer while it just not right to go directly ask developer to execute change without contacting designer team first.

**Describe the solution you'd like**
It will be more convenient to have interface in MyWonder so that designer can directly make the change without involving backend developer

**Describe alternatives you've considered**
Access to parameterized file or folder location where content can be replaced

**Additional context**
None

**Task**
- [x] 1. Analyze requirement with regard to existing design of MyWonder (doc: MyWonder v.1 Enhancement Specification)
- [x] 2. Design the feature (doc: MyWonder v.1 Enhancement Design)
- [x] 3. Implement feature to MyWonder
- [x] 4. Create scenario test
- [x] 5. Unit test and fix (doc: Bugs list and retest documentation)
- [ ] 6. Acceptance test

**Comment by nandrian-usc** [comment]
Will not do this during this release
