### ISSUE TITLE
Make examples of each visualization for testing and demo

### ISSUE THREAD

**Issue by nandrian-usc** [Khider-GarijoCORP/MyWonder_App#7]
**Is your Task related to any problem? Describe**

**Proposed Solution**

**Additional Note**
Don't forget to save examples into separate configuration files so that every time we need to reset testing environment for demo purpose then we don't have to manually reinput examples again.

**Task**
- [x] Allocate workload to everyone for examples input
- [x] Input examples to testing environment
- [x] Save configuration and examples data to files for future reset
- [x] Add examples to documentation (user guide)
